version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/var/www
    command: php artisan serve --host=0.0.0.0 --port=${PORT}
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: secure_drop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ifeoluwa
    ports:
      - "5432:5432"
